### ISSUE TITLE
Cannot place/break blocks with pet on head

### ISSUE THREAD

**Issue by MegaNarwhal** [Shynixn/PetBlocks#10]
When you put a pet block on your head, you can't place or break blocks because the armor stand is in the way. Not sure if this can be fixed but thought I should report it.

**Comment by Shynixn** [comment]
Thanks for reporting. I'll do some testing if I can find a workaround.

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-6.0.1-20170715.122621-1-jar-with-dependencies.jar
