### ISSUE TITLE
Cannot spawn Pet when using SpongeForge

### ISSUE THREAD

**Issue by Jaackla** [Shynixn/PetBlocks#123]
![screenshot_4](https://user-images.githubusercontent.com/36846537/39103427-8b152e36-46a2-11e8-9f07-025b73dd239b.png)

So im running a pixelmon reforged server so all pokemom mobs are turnt off as well
but i can spawn animals like chickens etc

PetBlock disabled and if i click it to enable it i get a error in the console, i clicked on engines and clicked a pet as well which worked but then i cant do nothing with it

**Comment by Shynixn** [comment]
This error appears when the pet is not able to spawn. Seems like something happend when hooking into nms of 1.12, in this case, the entity registry. What kind of configuration are you running on your server? sponge, pixelmon, etc.

**Comment by Shynixn** [comment]
Seems like forge messes with the Vanilla Entity Registry and removes the default registry field, so PetBlocks cannot register itself. As I don't want to reference the ForgeAPI in PetBlocks, I still need to find out where Forge handles entity registration.
