### ISSUE TITLE
Add Sponge 1.10.2 support

### ISSUE THREAD

**Issue by Brend-Smits** [Shynixn/PetBlocks#125]
Heey, 
First of all I would like to thank you for making this plugin Sponge compatible (1.12), it looks absolutely amazing! 
I was wondering if you are considering making a SpongeForge 1.10.2 compatible version? Maybe modded minecraft servers still have 1.10.2 servers as the majority of the userbase has not switched to 1.12 yet. 
Sponge 1.10.2 uses Sponge API 5 instead of 7.

Thank you in advance, keep up the good work!

**Comment by Shynixn** [comment]
Hi Rubbertjuh, 

First of all, thank you! I'm still new to the whole Sponge and Forge community so I appreciate any feedback I can get. Supporting multiple versions shouldn't be a problem, I have considered this when making the sponge port.

**Comment by Shynixn** [comment]
This issue is getting closed because times change.
