### ISSUE TITLE
We can take the pet in the offhand.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/PetBlocks#128]
Hey,

We can take the pet in the offhand.
Using Paper Spigot 1.12.2 and Java 8.

Thanks.

**Comment by Shynixn** [comment]
`pet:
  follow:
    carry: false`

Set carry to false.

**Comment by TheIntelloBox** [comment]
In the config ?

**Comment by Shynixn** [comment]
https://shynixn.github.io/PetBlocks/build/html/faq/candisablegrabbing.html
