### ISSUE TITLE
Spawning problem with SpongeForge

### ISSUE THREAD

**Issue by Jaackla** [Shynixn/PetBlocks#133]
Also on the 7.0.1 version
I type /petblock
Click the Engines to change the pet i have
Once i click the pet i want i then click the button that says Petblock Disabled and click to enable it
Once i do that i see the pet spawn for 1 second then it despawns and in the gui its turnt back to Petblock Disabled

Using Sponge Forge
 

![image](https://user-images.githubusercontent.com/36846537/39398803-1621f0f6-4b0b-11e8-81a5-75481eb7b05f.png)

**Comment by Shynixn** [comment]
Did you recreate the config.yml or added the lines as mentioned in the Developer Notes?

**Comment by Jaackla** [comment]
Okay i just deleted all the configs and let it regen them, no more errors while doing the toggle the pet stays out for about 2 seconds before vanishing now though. no errors in console

**Comment by Jaackla** [comment]
Yup done that, i installed the new version and deleted the whole config and let it regenerate with the new version, i have other mods on my server and i get no errors in the console now that i deleted the configs but when i spawn a pet it spawns for about 2 seconds then vanishes

**Comment by Dpa1991** [comment]
Running on spongeforge 3002 I get a similar issue, the pet will spawn and instantly despawn but I get this error in my console

`[19:47:05] [Server thread/INFO] [nucleus]: Dpa1991 ran the command: /petblock 
[19:47:07] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomGroundArmorstand
[19:47:07] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomRabbit
> 
`

**Comment by BrainStone** [comment]
I can confirm this issue:

```
> [03:42:21] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomGroundArmorstand
> [03:42:21] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomRabbit
```

Versions:

PetBlocks: 7.0.1
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-a312749
SpongeForge: 1.12.2-2655-7.1.0-BETA-3051
Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
Well this message has nothing todo with pets not spawning, it simply means that it isn't registered in the ordinary sponge registry. I'm going to register it there though as the warning disappears afterwards. It is only necessarry to register it in the entity packet registry for server entities which is not working for Forge**Clients** on 1.12. They get an error message and cannot connect to the server.

**Comment by BrainStone** [comment]
Anyways, the pet spawns for like one tick and then despawns. #134 might be the same issue.

**Comment by Shynixn** [comment]
I'll close this issue and move all discussions related to this to #134.
