### ISSUE TITLE
Reload command.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/PetBlocks#135]

**Comment by Shynixn** [comment]
Is /petblockreload not working or what do you want to say?

**Comment by TheIntelloBox** [comment]
Sorry I didn't know that there was a /petblockreload, you can close it.

**Comment by Shynixn** [comment]
No problem, seems like I have hidden the commands on this page https://shynixn.github.io/PetBlocks/build/html/customizing/commands.html instead of putting it into the commands category.
