### ISSUE TITLE
Make PetBlocks API easier to use

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#137]

**Comment by BrainStone** [comment]
As a recommendation:

You could make all calls that should be executed async return a `CompletableFuture`.

**Comment by Shynixn** [comment]
Thanks, I'll think about this.

**Comment by Cryptite** [comment]
Not entirely sure if this is the proper Issue to post this in, but the API documentation seems lacking in describing how to, for example, set the engine of a petMeta. How does one acquire an engine without a player?

The way I'm intending to use the API is to have my own definition of what makes a pet, and then construct a PetMeta at pet-spawn time, rather than give a player a single pet that they can then customize at will. I have put together an engine for a pet, we'll call it id 0, but am unsure how to actually get that engine via the API.

**Comment by Shynixn** [comment]
The engine is currently bound to the engine id specified in the config.yml which is not a good solution. Big API changes (losing backwards compatibility) are incoming along with #44. Still, this update will take a while, so the 1.13 update will hit a way earlier than these features.

**Comment by Cryptite** [comment]
Well that's not a huge problem for now. I suppose my question is, programatically, how does one do something akin to getEngineById(1) so that I can use it to apply to a PetMeta?

**Comment by Shynixn** [comment]
Well this isn't exposed to the API and handled internally, so I won't recommend this. Hook into the petblocks-sponge-plugin or petblock-bukkit-plugin part and access the controller Config.INSTANCE.getEngineController() (I'm using pseudocode here). Then cal lpetMeta.setEngineContainer(container, overwrite = true).

**Comment by Cryptite** [comment]
That seems to nearly work. This is what I have so far as a sort of "Spawn Pet given an engine id", however it doesn't always seem to take, nor does the name seem to change. What am I missing here?

`Optional<PetMeta> fromId = metaController.getFromPlayer(player);
        if (fromId.isPresent()) {
            PetMeta petMeta = fromId.get();
            petMeta.setPetDisplayName(currentPet.friendlyName);
            Optional<EngineContainer<GUIItemContainer<Object>>> engine = Config.getInstance().getEngineController().getContainerFromPosition(currentPet.engineId);
            engine.ifPresent(guiItemContainerEngineContainer -> petMeta.setEngine(guiItemContainerEngineContainer, true));
            petMeta.setSoundEnabled(false);
            Bukkit.getScheduler().runTaskAsynchronously(plugin, () -> {
                metaController.store(petMeta);
                Bukkit.getScheduler().runTask(plugin, () -> {
                    final PetBlock petBlock = petBlockController.create(player, petMeta); //Spawn PetBlock
                    petBlock.respawn();
                    petBlock.teleport(player.getLocation());    //Teleport the petblock to the target location
                });
            `});`

**Comment by Shynixn** [comment]
I can only add again that this is a dirty hook. If the API was ready ready for this, this issue wouldn't exist.

Maybe you can move the setDisplayName after setting the engine and the respawn() method is not necessarry to call if you create a new PetBlock via the controller.

**Comment by Cryptite** [comment]
Looks like I have just about everything working now. The only real thing that I can't seem to get working is updating the ParticleMeta on a pet; it just doesn't seem to take.

I'm able to grab one from CONFIG alright, but in this code; they don't ever update: https://pastebin.com/mEB9GpQq

Lastly, is there any way to determine, on a CreatureSpawnEvent, that said entity spawn was a PetBlock spawn? I know it's a CUSTOM spawn reason, but I need a little bit of something else so I can know not to cancel it within my own plugin for stuff.

Cheers!

**Comment by Shynixn** [comment]
Remove the PetBlock and recreate it if you want to be sure. 

All PetBlock entities contain a fixed meta data value called "keep". I haven't tested it but something similar should work.

`  Entity entity;
        Plugin plugin = Bukkit.getPluginManager().getPlugin("PetBlocks");
        for (final MetadataValue metadataValue : entity.getMetadata("keep")) {
            if (metadataValue.getOwningPlugin() == plugin) {
                // Is PetBlock entity.
            }
        }`

**Comment by Cryptite** [comment]
Just for my own sanity, what would you recomment is the right order of operations to "remove the petblock and recreate it"?
