### ISSUE TITLE
Changing the Enginge changes the Skin

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#141]
When a player changes the engine of the pet, the Skin changes to the Skin of the engine. While I see that that would be inteded, a config option to disable this behavior would be nice!

PetBlocks: 7.0.1
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-a312749
SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
The PetBlocks wiki does not explicity state this but there is the following config option.

# settings-copy-skin: Should the skin of petblock-engine be applied when being selected?

`gui:
  settings:
    copy-skin: true`

**Comment by BrainStone** [comment]
Ahhhh. Thank you :) 👍
