### ISSUE TITLE
When using the pet as a hat it cannot be unmounted

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#142]
When I use the pat as a hat, I cannot get it off my head, unless I disable and reenable it.

Versions:
- PetBlocks: 7.0.1
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-a312749
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
I need to check this again but I'm quite sure that it worked on my forge server.
