### ISSUE TITLE
Pet displayed too high when riding or using it as a hat

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#143]
When using the pet as a hat, it displays too high. When I ride it, I'd expect to be higher on the pet (be on top, not inside it)

Screenshots:

![2018-05-07_12 21 52](https://user-images.githubusercontent.com/4106544/39697466-53315292-51f1-11e8-8501-704dd391d066.png)
![2018-05-07_12 22 09](https://user-images.githubusercontent.com/4106544/39697467-534c092a-51f1-11e8-9b3c-1042e4427bd7.png)

Versions:
- PetBlocks: 7.0.1
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-a312749
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
That's simply because of the default hitbox of the Armorstand. It is only possible to make riding a little bit better by adding another small entity (endermite) between the player and the armorstand, however the amount of possible issues would increase drastically.
