### ISSUE TITLE
Pet sometimes despawns when changing the Engine

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#145]
Sometimes when changing the engine, the pet just despawns.

Versions:
- PetBlocks: 7.0.1
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-a312749
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
The pet should despawn and respawn when changing the engine but #134 says sometimes the pet does not spawn. I'll leave this issue open but it suffers the same problem.
