### ISSUE TITLE
[Feature] Allow opening of the GUI through the API

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#151]
It would be very cool to allow the GUI to be opened through the API. My main use for this would be giving the player an item that they can directly open the GUI with.

**Comment by BrainStone** [comment]
I know that I could just run a command to achieve that, however I think that is a pretty dirty hack and would much prefer an API call.

I mean it doesn’t have a huge priority to me, but it would be nice to have.

**Comment by Shynixn** [comment]
I would actually say exactly the opposite as the GUI is not meant to be exposed to the PetBlocksApi. I can leave this issue open but I don't think I will priorities this.

**Comment by BrainStone** [comment]
I mean I'm not asking for the ability to be able to work directly with the GUI. Just to have a clean call to open the menu.
