### ISSUE TITLE
[Feature] PetMeta updated event

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#152]
It would be really cool to have a PetMeta updated event, so I can refresh the item of a player when the pet has been changed.

Also I have a question: Assuming the PetMeta is not set through the API to a different object, will it remain the same object and is therefore safe to cache?

**Comment by Shynixn** [comment]
The same PetMeta instance is getting kept alive as long as the player has got a valid spawned PetBlock. If the player does not have a spawned PetBlock the PetMeta is queried each time it is required from the database. The reason behind is that the PetMeta contains a tickcounter which is increased by the PetBlock instance and the other reason is that a player might not want to access the PetMeta at all during his game session, so it would be pointless to keep it in RAM.
