### ISSUE TITLE
HeadDatabase issue

### ISSUE THREAD

**Issue by Blackyvk** [Shynixn/PetBlocks#163]
Let me rewrite, 

if I dont give them the buy node they can use the heads with petblock
If i ive them the buy node, they have to pay to use the heads from petblock

this could be an issue for servers that sell the heads but also want to let players use them for free on their pets

also i dont see a way to disable categories from the HDB to be used on petblocks

**Comment by Shynixn** [comment]
So... what do you want to change in your opinion?

**Comment by Blackyvk** [comment]
both plugins should work with their own permissions, because right now petblock needs headdb permissions to work and use its heads.

If I want to sell heads from head database, petblock shouldnt be charging users to use headdb heads.

**Comment by Shynixn** [comment]
ok, but PetBlocks only has got one permission for Headdatabase as it does not know which user has got which permission to use which head. Just give your player this permission and PetBlocks can open the Headdatabase GUI and Headdatabase deals with the rest. 

"Allows to use all head database costumes | petblocks.selection.headdatabasecostumes.all"

**Comment by Shynixn** [comment]
Anything else you want to add? @Blackyvk Otherwise I would close this issue?

**Comment by Blackyvk** [comment]
No thanks
