### ISSUE TITLE
SpongeForge/Pixelmon Petblocks floating constantly.

### ISSUE THREAD

**Issue by Vohras2** [Shynixn/PetBlocks#167]
We are currently running Sponge 3206 and Forge 2705, as well as the latest recommended version of Pixelmon. Upon spawning in, the petblocks seem to float constantly in the air, never touching the ground. As such, they constantly do a warping effect at eye level upon movement, making it difficult to see at times. The wear on head feature also seems to not function properly, as players are unable to remove the creatures from their head upon activating it.

**Comment by Shynixn** [comment]
#134 
https://shynixn.github.io/PetBlocks/build/html/gettingstarted/installing.html#spongeforge

I see, thanks for letting me know about your experience with SpongeForge and PetBlocks. It's difficult to tell you any kind of solution as I'm experiencing no or other problems. Maybe I'll really need to a client mod so Pets get correctly synchronized on SpongeForge.

**Comment by Rasgnarok** [comment]
It actually shouldn't require a client mod at all, if it works with spigot properly. I think the matter is that the entity, the pet block, is moving ahead and over the player instead of trailing behind, almost as if you pegged the path of the petblock to the player instead of following.

I would suggest joining the sponge discord:  https://discord.gg/PtaGRAs to ask them how to fix this, I am fairly certain a client mod wouldn't be needed to fix the positioning/latency of the pet block.

**Comment by Rasgnarok** [comment]
From @Vohras2 's account, it feels to me as if the pet blocks are starting out as hats, and can never be dismounted properly... maybe start there?

**Comment by Shynixn** [comment]
I have got no problems with SpongeVanilla and I can tell you that this issue is not Sponge related but Forge. Did you click on my referred links? 

Also, as I said I can properly mount and dismount my pets on a SpongeForge server with Pixelmons installed. The problem is a bit more complex than you might expect. Nevertheless thanks for your help.

**Comment by Shynixn** [comment]
Forge on the client actually changes some kind of entity checking as mentioned on the linked pages.

**Comment by Rasgnarok** [comment]
Yes, I indeed did, but I did not really see the connection - spawning is fine and there are no errors in console. It is bizarre you are specifically having issues with Spongeforge when they both share the SpongeCommon and SpongeAPI, but well, it's not like I use Vanilla much.

I do not think, unlike what OP states, that it has anything to do with Pixelmon, as this can be probably be replicated on an Spongeforge only server.

Regarding the mounting issue, what Sponge build are you testing? the 3206 RB is _vastly_ different to the latest SF build (3323?). I'd like to compare your testing to mine, as I am able to reproduce both issues 100% of the time.

**Comment by Rasgnarok** [comment]
and, on your Spongeforge test server, where do the entities float? Above the player's head or trailing behind as expected? This would really help me test with later Spongeforge as well. Thanks.

**Comment by Shynixn** [comment]
You are right, I think I haven't tested it with the latest build. Because the Sponge Layer is completely irrelevant for the pet entities. Forge just uses another approach with entities than SpongeVanilla. Also, the client mod Forge contains more entity restrictions than Vanilla Minecraft.

**Comment by Rasgnarok** [comment]
I understand, I am just simply stating the last ~200 commits have significantly altered the Sponge tracker along with a few other entity related sections, and it would be just good debugging to properly test.

What SF build were you testing with? If you were having no issues with the petblocks mount command or its entity positioning, as you said earlier, I'd like to reproduce my findings on the SF you used.

**Comment by Shynixn** [comment]
The build I was testing was very old so it caused some problems. 

Unfortunately I cannot confirm your mentioned issues with the latest version 7.2.0. Can you try to test it again? I have added my used configuration to the wiki page. 

https://shynixn.github.io/PetBlocks/build/html/gettingstarted/installing.html#spongeforge

**Comment by Rasgnarok** [comment]
So just to confirm, you are testing with Spongeforge 3361 and Forge 2705?

**Comment by Shynixn** [comment]
Yes, I have tested the latest release v7.2.0 with this configuration.
