### ISSUE TITLE
Coloured Title Stops Menu from Functioning

### ISSUE THREAD

**Issue by RJHaytree** [Shynixn/PetBlocks#171]
Hey there, Shynixn,

I'm having a slight issue when testing the plugin in the following environment: 

SpongeForge: spongeforge-1.12.2-2705-7.1.0-BETA-3358
Plugin Build: https://ore.spongepowered.org/Shynixn/PetBlocks/versions/7.1.0/download (Appears to be latest)

The issue I'm having is that whenever I add a colour code to the menu's title, none of the buttons continue to function after reloading the plugin. If you remove these colour codes, the plugin works as intended once again. One of the combinations I was testing with is `title: '&6&lPet&d&lBlocks'`, which does appear in the GUI, but the buttons do not function.

Hopefully this issue is easy to resolve, especially with all the issues I can see arising when you update the plugin to 1.13.

Sincerely, merjilin

**Comment by Shynixn** [comment]
Thanks for reporting. I'll take a look into this.
