### ISSUE TITLE
[7.2] NoSuchElementException: at com.github.shynixn.petblocks.sponge.logic.business.service.GUIServiceImpl

### ISSUE THREAD

**Issue by Rasgnarok** [Shynixn/PetBlocks#177]
Sponge version: 3361/3358 (aka above RB 3206)
PetBlocks version: 7.2

Error: https://pastebin.com/rtnWkaus

[debug.log](https://github.com/Shynixn/PetBlocks/files/2259782/debug.log)
[latest.log](https://github.com/Shynixn/PetBlocks/files/2259783/latest.log)

As spoken over your discord, here's the bug report! On a populated server, it can get pretty spammy and cause a timeout. Let me know if you need more information!

**Comment by Shynixn** [comment]
Thanks for reporting, I think I have got enough information to resolve it. 
ClickInventoryEvent$Drop$Outside$Primary$Impl probably stands for a dropping event.
