### ISSUE TITLE
Trying to ride the pet causes server to shutdown

### ISSUE THREAD

**Issue by cenaamil** [Shynixn/PetBlocks#205]
If someone tries to ride the pet, the server immediately shutdowns. Using latest version of craftbukkit

**Comment by Shynixn** [comment]
Hi @cenaamil, can you please provide the error log which caused the crash.

**Comment by cenaamil** [comment]
https://pastebin.com/PX0fQR7m

**Comment by Shynixn** [comment]
@cenaamil Please use the latest stable version of PetBlocks. You can find the direct download on the releases page of PetBlocks.
