### ISSUE TITLE
Problem when /petblock ?

### ISSUE THREAD

**Issue by TonyoBlaster** [Shynixn/PetBlocks#206]
Impossible to do the /petblock ? Is it a problem for the compilation with recents compilations from Forge/Sponge ?

![image](https://user-images.githubusercontent.com/40760363/51928212-aa24aa00-23f5-11e9-9aae-e21ad0071138.png)

**Comment by Shynixn** [comment]
Seems like Spongeforge fails to apply the access tranformations of my plugin. This might be the problem of another plugin modfiying them. Could be a version problem too. https://docs.spongepowered.org/stable/en/plugin/internals/access-transformers.html?highlight=transformer
