### ISSUE TITLE
Inventory can't be edited after using menu

### ISSUE THREAD

**Issue by Stampede2011** [Shynixn/PetBlocks#235]
My apologies if this is already a known issue or an issue on my end. Before opening the menu, you can move things in your inventory around just fine. Once you open the inventory however, everything in your inventory cant be moved or removed but things can be added. Video below.

Specs:
Forge 1.12.2 2705
SpongeForge 2705-7.1.0
Latest version of Petblocks (v8.0.1)

[https://www.youtube.com/watch?v=0AXjTD-y6zY&feature=youtu.be](url)

**Comment by Shynixn** [comment]
No, this issue was not reported yet. 
Thank you for the detailed description and video, I'm going to analyze and fix this!

Can I tag @Stampede2011 you once a snapshot build fixing this issue is available?

**Comment by Stampede2011** [comment]
Of course! Let me know.

**Comment by Shynixn** [comment]
@Stampede2011 

Should be fixed :)

https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-sponge-plugin/8.0.2-SNAPSHOT/petblocks-sponge-plugin-8.0.2-20190414.130404-2.jar

**Comment by Stampede2011** [comment]
Looks like it works perfectly! Tested it thoroughly and didn't see the issue at all.

**Comment by Vionai** [comment]
I'm also having this issue.
