### ISSUE TITLE
PetBlocks-Sponge is not compatible to PotionCore - Right clicking pets picks them up

### ISSUE THREAD

**Issue by Dpa1991** [Shynixn/PetBlocks#238]
It seems any player can rightclick a petblock and pick it up as a minecraft head block with the texture leaving a floating <player> pet tag where the block once was I havent tested it too much but I am running version 8.0.1

**Comment by Shynixn** [comment]
Hi,

Can you please add the following information:
- server information
- minecraft version
- Under which circumstances does the error appear (Rightclicking the pet is the first thing I'm always testing)

**Comment by Shynixn** [comment]
@Dpa1991 I'm particularly intersted in this.

**Comment by Dpa1991** [comment]
Sorry I was going to test some more and grab info yesterday but I got busy, had no computer access yesterday. Going to test some more I have a theory its related to the quark mod changing something.. or because I'm using an older version of spongeforge (mod limitations requires it for now)

**Comment by Dpa1991** [comment]
Alright I've narrowed the issue down to PotionCore-1.6_for_1.12.2 and QualityTools-1.0.6_for_1.12.2. With those mods loaded pets can be picked up by anyone.. without them, your plugin works as intended. Guess I should be talking to their devs, or maybe you can figure it out Idk

**Comment by Shynixn** [comment]
Thank you for analyzing this! I also tried running PetBlocks with your configuration and I can confirm that installing PotionCore breaks the SpongeEvents regarding interacting with entities. Probably, I won't be able to fix anything on my side as the call from Sponge never reaches my plugin. There might be some compatibility problems with SpongeForge and PotionCore?

**Comment by Shynixn** [comment]
Closing this in favor of #243 .
