### ISSUE TITLE
Error when new player joins to the server

### ISSUE THREAD

**Issue by MorkaZ** [Shynixn/PetBlocks#242]
I have this error in console when new player joins to my server:
https://pastebin.com/MttzHu5F

**Comment by Shynixn** [comment]
Seems like the ais do have a registration problem, however this should be handled by the plugin. Thanks for reporting, I'll fix this.

**Comment by MorkaZ** [comment]
Will it be fixed in near future :P? I want to use your plugin. Thanks.

**Comment by Shynixn** [comment]
I'm quite busy right now, but it is in my focus.
