### ISSUE TITLE
When trying to set skin from head database plugin, error is thrown

### ISSUE THREAD

**Issue by MorkaZ** [Shynixn/PetBlocks#244]
I am trying exactly this:
https://shynixn.github.io/PetBlocks/build/html/customizing/headdatabase.html?fbclid=IwAR2hGBdw6uIUJ_-qQVkLgdwA-syNaxp6074kqTZtGd0hBke4_zIkOw8r-d4
And get this error:
https://pastebin.com/nRXGr1Ue
Everything latest (latest spigot 1.13.2)

**Comment by Shynixn** [comment]
PetBlocks needs to get the gui title of the HeadDatabase GUI and loads it from the config.yml of the HeadDatabase plugin. Specifically PetBlocks fails to parse the messages.database text from the config of the HeadDatabase plugin. Can you please check if the default config.yml is working?
