### ISSUE TITLE
CreatureSpawnEvent error from WorldGuard integration

### ISSUE THREAD

**Issue by leothawne** [Shynixn/PetBlocks#247]
Hello! I'm currently using PetBlocks v8.1.0 and WorldGuard v7.0.0-beta-03;e51a220 and the problem I'm experiencing is:

Whenever I or another player enables its pet, this error is thrown in the console: [https://pastebin.com/HZkXkyqt](https://pastebin.com/HZkXkyqt)

Could you take a look at that and see if you can fix it, please? Thank you <3
I'll be here waiting for any answer.

**Comment by Shynixn** [comment]
Thanks for reporting. This will we fixed along with #245.

**Comment by Shynixn** [comment]
Actually, I have taken a look at the worldguard/worledit source code and it is a bug in the EntityTypes implementation of WorldEdit. I'll implement a workaround in PetBlocks.
