### ISSUE TITLE
JDBC Driver not found

### ISSUE THREAD

**Issue by HeberonYT** [Shynixn/PetBlocks#255]
I have configured the MySQL option but the plugin has an error connecting to the DB.

LOG: https://pastebin.com/raw/sE9Pg2xr

spongeforge-1.12.2-2768-7.1.6-RC3682.jar
petblocks-sponge-plugin-8.3.1-20190606.211151-4.jar

**Comment by Shynixn** [comment]
Seems to be a minor configuration issue in the code. Thanks for reporting, should be fixed soon.

**Comment by HeberonYT** [comment]
This is fixed in the Snapshot `petblocks-sponge-plugin-8.3.1-20190608.112741-6.jar`
