### ISSUE TITLE
[Feature Request] MySQL customizable table prefix

### ISSUE THREAD

**Issue by BobbyKilkins** [Shynixn/PetBlocks#262]
This is an incredibly fast/easy addition, but would make things much easier.
Since MySQL (which most plugins use) doesn't have schemas, tables have to be sorted by prefixes. While other plugins can be shortened/changed for easier administration, the petblocks prefix can't. It is also very confusing (SHY)
Example:
LuckPerms -> lp_table
PlotSquared -> plot_table
CoreProtect -> co_table
PetBlocks -> SHY_table

**Comment by Shynixn** [comment]
I think it is a good approvement to add a prefix option to the config.yml. However, the tables are prefixed with SHY as some are interchangeable with other plugins of me.
