### ISSUE TITLE
plugin dont working in 1.14

### ISSUE THREAD

**Issue by ProDash1998** [Shynixn/PetBlocks#290]
[23:04:56 WARN]: Plugin PetBlocks v8.8.0 does not specify an api-version.

i use paperspigot 1.14.4 build 207

**Comment by Shynixn** [comment]
This warning can be ignored as PetBlocks supports multiple minecraft version but spigot does not like that. 
PetBlocks should be working in 1.14.4 but a common issue with the latest paper-spigot version is that you need to enabled `armorstand-ticking: true` in your paper.yml.

**Comment by ProDash1998** [comment]
i have enabled. if i use /pet /pets plugins dont open gui

**Comment by Shynixn** [comment]
Did you change the command? The default command is /petblock.
