### ISSUE TITLE
OpenSource Contributions

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#298]
### OpenSource Development 2019

This project always needs some help with minor tasks. 
If you are a OpenSource contributor, you have found a project which provides explained and easy tasks for you :)

### Guidlines

**Required Knowledge**
* Java/Kotlin
* Common knowledge about the Bukkit API

**Code/Style/Architecture**
* Please use the existing layout of the project and avoid creating packages.
* Keep consistency over the whole project.

### Getting started

* Look for a task below which you would like to do
* Create a new issue with the task name
* Fork and clone the repository to your local pc
* Use the [contributing description](https://github.com/Shynixn/PetBlocks#contributing) on the README to setup required dependencies in order to build the project.
* Work on it :)
* Submit a pull request when you are done to initiate a reviewing process

### Tasks

**It is highly recommend to create a new issue on this project with the task name for example "Refactor convertChatColors" to avoid duplicate task pull requests.**
  
### Open Tasks

- [ ] Implement the localization service
* Our players would like to have messages separated from the config.yml where all messages are stored in English. Multiple different files like en.lang, de.lang files should allow to easily define localized messages. In order to achieve this behaviour we need a new cross platform service in PetBlocks. 
* Add the finished interface below to the `com.github.shynixn.petblocks.api.business.service`package.

```kotlin 
interface LocalizationService {
    /**
     * Reloads the localization.
     */
    fun reload()
    /**
     * Tries to load the localization value from the given [path].
     * Throws a [IllegalArgumentException] if the path could not be correctly loaded.
     */
    fun findText(path: String): String
}
````

* Add a new class called LocalizationServiceImpl to the ``com.github.shynixn.petblocks.core.logic.business.service`` package and implement the above interface in it. The constructor of this class takes 1 parameter: ``ConfigurationService``. (Take a look at the other classes in the same package)
* The class will cache the localization in a field of type [java.util.Properties](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html) 
* The ``reload()`` method is going to refresh the data from an existing file into this field. (Path: ``configurationService.applicationDir/lang/en.lang)
* The ``findText(..)`` method is going to call the ``findValue(..)`` method to obtain a String. Check if this string is a property key and return the matching value if it . Otherwise, just return the String.
* Make sure both methods are correctly implemented as described above
* Make sure the project still compiles aferwards.

**Comment by anihadh** [comment]
Don't know how this works but I've created a pull request

**Comment by Shynixn** [comment]
It is not necessary to fully understand the program in order to contribute to it.

**Comment by anihadh** [comment]
I meant I'm new to Github. Thank you for this opportunity :)

**Comment by Shynixn** [comment]
Good job, welcome to github :)
If you are interested, I have got a slightly more advanced task at my BlockBall repository.

**Comment by anihadh** [comment]
Thanks. Yeah I'm interested. Trying to earn that Hacktoberfest t-shirt, but I'm having trouble finding tasks I can do

**Comment by Shynixn** [comment]
Added a new task

**Comment by anihadh** [comment]
Where do I find the Slime interface? or how do I find out which functions to remove?

**Comment by Shynixn** [comment]
@anihadh  Implementing the Slime interface is no longer necessary. For version 1_8_R1 for example:
https://github.com/Shynixn/PetBlocks/blob/0e462655ab755a7c7ad291010915f41daaef776d/petblocks-bukkit-plugin/petblocks-bukkit-nms-108R1/src/main/java/com/github/shynixn/petblocks/bukkit/logic/business/nms/v1_8_R1/CraftPet.kt#L38

The compiler will highlight the functions in red.

**Comment by archery2000** [comment]
Hi, I'm new to open source, and I'm looking to help out. Is there anything I can do for this issue? :)

**Comment by Shynixn** [comment]
Hi @archery2000, also welcome to github :) I think @anihadh is taking on the open task? Anyway, I might have got more tasks later this week/month.

**Comment by archery2000** [comment]
Sure! I have a bit of experience with minecraft mods although that was some time ago, and with Forge

**Comment by anihadh** [comment]
Um.. this week's gotten really busy for me, and I might not get the time. So @archery2000, if you want to do this one, go ahead

**Comment by archery2000** [comment]
Ok, I'll work on it. Thanks!

**Comment by archery2000** [comment]
@Shynixn opened a pull request (#303) to close #301

**Comment by Shynixn** [comment]
Added a new task!
