### ISSUE TITLE
Feed to continue buff (and other ideas)

### ISSUE THREAD

**Issue by tacocoma** [Shynixn/PetBlocks#323]
Much needed feature:
It's a very simple idea- adds a configuration for Feeding/BuffEffect ais to make it so that users have to feed their pet every x seconds to continue receiving buffs. There would be a bar below the pet's nametag or in the /petblock menu that shows how long they have until next feed.
I think more features that incentivize users to "manage" their pet would make this plugin a lot more interesting. 
If the pet had health and an ai to block enemy attacks (eg jumping in front of a skeleton's arrow) or similar ai like the one below:

A way for pets to attack enemies through stunning them from moving OR shooting a particle shot at them would be awesome too, but this is a big request I'm sure. Only mythicmobs has been able to execute this perfectly for custom enemies.

**Comment by tacocoma** [comment]
I had an idea after writing this post- if you could just add a "target" configuration for the buff-effect you could have certain potion effects target enemies or multiple players.

**Comment by Shynixn** [comment]
Hm.. Interesting concepts. I need to take a look at how these 2 ais should be able to interact with each other but in general I like this idea.

A targeting system is a great idea and PetBlocks needs one anyway for future ais. :)

**Comment by tacocoma** [comment]
Glad you like the ideas! This plugin is amazing I'm so glad I came across it :)
