### ISSUE TITLE
Support command aliases

### ISSUE THREAD

**Issue by tacocoma** [Shynixn/PetBlocks#324]
Hi, as far as I'm aware no one else has asked for this feature. I'm looking to change the alias for the /petblock command. /pet or /pb would work so much more smoothly for me. If there's any simple way to add this either on shynixn's time or my own it would be greatly appreciated!
Thank you

**Comment by Shynixn** [comment]
Currently PetBlocks  does not support the alias feature of commands. You can rename the command itself but adding aliases is not possible.

If you have got atleast basic Java knowledge you can fork this project and add this feature on your own. (Kotlin is very easy to get into for Java developers) Of course I would guide you what to do to get started.
