### ISSUE TITLE
Skin Paths not recognized when changing skins | <player> parameter not functioning

### ISSUE THREAD

**Issue by Repo31c** [Shynixn/PetBlocks#330]
Hello,

So there are three main issues with the skin paths feature.
FYI I followed your guide here - [LINK](https://shynixn.github.io/PetBlocks/build/html/commands/commandlist.html#petblocks-skin-path-player)

**1. Skin Paths are not Recognized**
- Commands used: /petblock skin mycustomskins.marioskin
- Result: Pet receives a steve or alex skin.
- Possible Issue: The plugin isn't recognizing the "." and assumes that "mycustomskins.marioskin" is the name of a minecraft player, rather than a path in the config.yml.

**2. When skin paths are recognized, I am unable to use regular names of players for skins.**
- Assumption: We are assuming that the plugin successfully recognized "mycustomskins.marioskin" and set the mario skin to the player.
- Commands used: /petblock skin MHF_Cow
- Result: An error message stating that it is not a proper pathway.
- Possible Issue: After recognizing a skin path, the plugin only recognizes names with a "."

**3. Using the <player> parameter opens up the petblock menu.**
- Commands used: /petblock skin MHF_Cow username
- Result: The command opens up the main menu rather than settings the skin.

**Comment by Shynixn** [comment]
Hi @Repo31c!
Thanks for your detailed description but is possible that you have used the wrong command? It's /petblocks compared to /petblock.

**Comment by Repo31c** [comment]
> Hi @Repo31c!
> Thanks for your detailed description but is possible that you have used the wrong command? It's /petblocks compared to /petblock.

Sorry, I meant /petblocks.

**Comment by Repo31c** [comment]
> Hi @Repo31c!
> Thanks for your detailed description but is possible that you have used the wrong command? It's /petblocks compared to /petblock.

Just tried it, I guess that "s" was the cause of the issue. Thank you
