### ISSUE TITLE
the rabbit is not removed

### ISSUE THREAD

**Issue by microwin7** [Shynixn/PetBlocks#347]
![image](https://user-images.githubusercontent.com/12544425/79697190-f9b8f500-8289-11ea-8758-a1eca9c6b273.png)
The rabbit remains after turning off pet's, it infuriates me that manages to him push me away player

**Comment by microwin7** [comment]
/mv purge all
writes that they are deleted, but in fact they don’t even disappear anywhere, even for a second, the sound of hens is constantly from these invisible pets, although he turned it off in the config

**Comment by Shynixn** [comment]
Hi @microwin7 !

Are we talking about PetBlocks-Bukkit or PetBlocks-Sponge?

**Comment by Shynixn** [comment]
This critical error occurs in all minecraft versions. Thank you for reporting, I'll immediately publish a snapshot fixing this issue.,

**Comment by microwin7** [comment]
Paper-Sigot-1.12.2

**Comment by Shynixn** [comment]
@microwin7  
Can you please try out the snapshot below?

https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-bukkit-plugin/8.16.0-SNAPSHOT/petblocks-bukkit-plugin-8.16.0-20200420.120414-4.jar

**Comment by Shynixn** [comment]
Also, you can remove all invisible rabbits by executing the /petblockreload command.

**Comment by microwin7** [comment]
Check, now everything is fine
