### ISSUE TITLE
Falling through the ground whilst riding a petblock

### ISSUE THREAD

**Issue by baailey** [Shynixn/PetBlocks#386]
Just as the title says, I have an issue with riding petblocks that will make me fall through the ground, all the way into the void. 

Here is the config: https://pastebin.com/cSFVt6cG

**Comment by LazoYoung** [comment]
This probably has something to do with https://github.com/PaperMC/Paper/issues/3401

**Comment by Shynixn** [comment]
Every PaperSpigot version +274 is affected
