### ISSUE TITLE
When feeding pets, it will cause server lag

### ISSUE THREAD

**Issue by apollogauss** [Shynixn/PetBlocks#416]
Game version spigot 1.13.2
When I wanted to feed my pet with more than one food, the server caused a lag.
It may be that there is no set interval for the feeding action.

**Comment by Shynixn** [comment]
Hi @apollogauss !

Interesting, I'll take a look. Can you post the spigot timings?

https://www.spigotmc.org/wiki/timings/

**Comment by Shynixn** [comment]
I tested it on my development server but I received "good" timings for feeding pets. 

If you do not provide timings or more information, I need to close this issue.
