### ISSUE TITLE
Add new behaviour entity "BAT" for flying pets

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#44]

**Comment by promorrom** [comment]
Sure, this will be awesome.

**Comment by FrankHeijden** [comment]
yes please implement this, would be great for birds and other flying pets instead of a bunny hopping bird o.O

**Comment by Shynixn** [comment]
Would not be that difficult but writing the NMS layer for **8** different minecraft versions is just exhausting.  I'll set it to the highest priority for the next major update.
