### ISSUE TITLE
Able to hold the pet menu items

### ISSUE THREAD

**Issue by baailey** [Shynixn/PetBlocks#440]
If you open the pet menu, you can obtain the items by clicking F whilst hovering over the item. It should put the item in your off-hand. Works in both GMC and GMS. However, in GMC you are able to move the item around the inventory, whereas in GMS the item disappears upon clicking it.

**Comment by Shynixn** [comment]
Hi @baailey !
Thanks for reporting, I'll check it. What do you mean with GMC and GMS? Gamemode create and gamemode spectator?

**Comment by baailey** [comment]
Creative and Survival is what I mean by GMC and GMS

**Comment by Shynixn** [comment]
I wasn't able to solve it on my own for now and submitted a bug report for spigot. 
https://hub.spigotmc.org/jira/browse/SPIGOT-6145
