### ISSUE TITLE
You die in the void when you ride and then dismount your pet at slabs/stairs that are far from solid blocks

### ISSUE THREAD

**Issue by CodeGourami** [Shynixn/PetBlocks#485]
Petblocks version: PetBlocks 8.24.0
Paper version: git-Paper-498 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

What I expected:
Not get teleported to the void when getting off my pet.
What happened: 
getting off my pet without solid blocks nearby teleports me to y level -170 

Ive changed nothing about the dismounting configuration. 

config: https://pastebin.com/b89pybTb

How to reproduce: 
1: Install Petblocks 8.24.0 
2: Make a platform of a non full block without having a lot of full blocks nearby (players often build with slabs and stairs, this was discovered when dismounting on a tower made of slabs and stairs)
This can be achieved by just towering up and making a platform of slabs in the air
3: Call and ride your pet
4: Sneak to dismount your pet and you die in the void

Platform example: 
<img width="931" alt="issue" src="https://user-images.githubusercontent.com/53400138/109366832-b7424a80-7894-11eb-83ff-d7da863c919c.png">

Let me know if you need any more information!

**Comment by baailey** [comment]
This issue occurs when dismounting on solid blocks as well, but only when an island, for example, is elevated high in the sky. The default terrain does not cause this issue for me.

[What I tried dismounting on](https://i.imgur.com/ZK2UoVU.png)

PetBlocks Version: 8.24.0
Server version: git-Tuinity-"4743c34" (MC: 1.16.4)
