### ISSUE TITLE
Java 16 Support

### ISSUE THREAD

**Issue by Cryptite** [Shynixn/PetBlocks#487]
Title explains it! 

Minecraft 1.17 will raise the minimum Java level for Minecraft to 16 and as such many servers like mine are trying to get ahead of it.

**Comment by Shynixn** [comment]
Hi @Cryptite ,
as far as I know this is not a problem for PetBlocks as it is backwards compatible back to Java 8. You should be already able to run PetBlocks on Java 16 and above. 
Anyway, the "new language features" of Java do not really apply to PetBlocks as PetBlocks runs mostly on Kotlin which is (in my opinion) still far superior compared to Java.

**Comment by Cryptite** [comment]
Hey there! 

There are serialization changes in JDK16 that cause issues for some plugins that do reflection, as such PetBlocks won't load on JDK16. I don't believe it's anything special with my environment: https://paste.gg/p/anonymous/a028924753bf434889951c5711f0ff85

**Comment by Shynixn** [comment]
Probably related to this issue and can be simply fixed by updating the guice dependency in PetBlocks.

https://github.com/google/guice/issues/1133
