### ISSUE TITLE
Introduce support for when going vanish

### ISSUE THREAD

**Issue by baailey** [Shynixn/PetBlocks#488]
Currently, when going vanish with a PetBlock enabled it will remain enabled and teleport with you to a player, for example. This is quite inconvenient if you forget about PetBlocks teleporting with you instead of auto disabling, and can 'expose' you if you're trying to investigate a mischievous player.

**Comment by Shynixn** [comment]
I think there are 3 types of invisibility in spigot-minecraft. Potioneffect invisibility, NBT tag invisibility, not sending player packets to other clients. 
If you say "vanish" what type do you mean?

**Comment by baailey** [comment]
Oh apologies, I’m referring to plugin support like /vanish 
 
In my case I’m looking for PremiumVanish support as that’s the plugin I use

**Comment by Shynixn** [comment]
I think PremiumVanish offers some placeholders over the placeholder API if someone is vanished or not. 
If you combine this with a plugin which executes commands when this placeholder changes, you could then execute ``/petblocks disable [player]``.

**Comment by baailey** [comment]
That’s something I could consider doing if you’re not interested in implementing vanish support. 

I believe PremiumVanish mentions a simple Bukkit API check for vanished players that doesn’t require any dependencies, if you are interested.

**Comment by Shynixn** [comment]
I avoid having too many dependencies in PetBlocks because if one of the dependencies breaks, PetBlocks also breaks and requires an update. 

Please try to achieve it with other interfaces first (e.g. plugins, placeholderapi), or develop your own small extension (Probably simply a listener on the PlaceHolderApi and calling pet.remove() if the vanish flag is true).

**Comment by baailey** [comment]
I have found a solution to my issue, so I'm all good now. However, the API PV recommends does not involve implementing any dependencies. It entirely utilises Bukkit and Bukkit only. 

`private boolean isVanished(Player player) {
        for (MetadataValue meta : player.getMetadata("vanished")) {
            if (meta.asBoolean()) return true;
        }
        return false;
}`

This is the vanish check suggested if you don't want any dependencies added to your plugin. Whether you use it not is entirely up to you.

**Comment by Shynixn** [comment]
Ok thanks. I'll keep it in mind and close this issue.
