### ISSUE TITLE
Deprecated Event

### ISSUE THREAD

**Issue by Dooleylabs** [Shynixn/PetBlocks#5]
It doesn't appear as if it'll affect gameplay, but a nasty little warning pops up on the plugin load that claims the method you're using to monitor chat input may cause lag to the main chat thread.

[Here's the output](https://hastebin.com/ayiwehevol.css); maybe there's a way you could suppress it?

Thank you.

Server Version: 1.11.2
Plugin Version: 5.7.0

**Comment by Shynixn** [comment]
Hey Dooleylabs, 

Nice plugin you have got there but the reported event is only registered as an option to support more chat plugins and is disabled by default in the config.yml. There won't be any performance boost if I remove it. 

I might remove it in the future though as it's deprecated-

**Comment by Dooleylabs** [comment]
Erm, if you mean nice plugin reffering to the output I linked, that's a default bukkit function from bukkit.yml, the option about deprecated plugins. Setting it to true shows output like I've provided.

**Comment by Shynixn** [comment]
I see, still thanks for reporting but it won't be removed any time soon :)
