### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by FockPanda** [Shynixn/PetBlocks#507]
Hola buenas tardes hace un momento estaba utilizando al plugin de las mascotas pero no me dejava aparecer , le daba al comando /petsbloock y me salia el menu , entonce le dava a la opcion de aparecer y decia que no estaba en un lugar adecuado me cambie de varios sitios pero la mascota segia sin aparecer

**Comment by Shynixn** [comment]
Please use English if you want to receive support.
