### ISSUE TITLE
Could not pass event EntitiesLoadEvent to PetBlocks v8.29.0

### ISSUE THREAD

**Issue by baailey** [Shynixn/PetBlocks#524]
15.12 23:11:39 [Server] ERROR Could not pass event EntitiesLoadEvent to PetBlocks v8.29.0
15.12 23:11:39 [Server] INFO java.lang.IllegalStateException: Chunk not there when requested: Unloaded [-502, -200] Unloaded [-496, -192] Unloaded [-497, -191] Unloaded ticket level [-505, -199]
15.12 23:11:39 [Server] INFO at net.minecraft.server.level.ServerChunkCache.lambda$getChunk$13(ServerChunkCache.java:681) ~[?:?]
15.12 23:11:39 [Server] INFO at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[paper-1.18.jar:?]
15.12 23:11:39 [Server] INFO at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:677) ~[?:?]
15.12 23:11:39 [Server] INFO at net.minecraft.world.level.chunk.ChunkSource.getChunk(ChunkSource.java:14) ~[?:?]
15.12 23:11:39 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.getChunkAt(CraftWorld.java:300) ~[paper-1.18.jar:git-Paper-66]
15.12 23:11:39 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftChunk.getEntities(CraftChunk.java:128) ~[paper-1.18.jar:git-Paper-66]
15.12 23:11:39 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.listener.EntityCleanUp117R1Listener.onEntityLoad(EntityCleanUp117R1Listener.kt:16) ~[PetBlocks-Bukkit.jar:?]
15.12 23:11:39 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]
15.12 23:11:39 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
15.12 23:11:39 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-66]
15.12 23:11:46 [Multicraft] Skipped 36 lines due to rate limit (60/s)

Plugin version: 8.29.0
Server version: git-Paper-66 (MC: 1.18)

**Comment by Shynixn** [comment]
I think that's an actual of the implementation. I'll publish a fix.

**Comment by Shynixn** [comment]
Can you please try the release https://github.com/Shynixn/PetBlocks/releases/tag/8.29.1 and take a look if the problem was fixed? @baailey

**Comment by baailey** [comment]
Unsure how the error is caused, so will give it a few days before letting you know the results.
