### ISSUE TITLE
Permissions per pet

### ISSUE THREAD

**Issue by JimmyBinoculars** [Shynixn/PetBlocks#540]
You could say that this is not an issue but I think that each pet should have a permission for the player to be able to use it.
A way you could do this is by using the player head id

this is useful for monetized servers to be able to sell pets

**Comment by JimmyBinoculars** [comment]
If this is already possible I don't know haw so please inform me

**Comment by Shynixn** [comment]
Yes, this is already possible. You can add a ``permission: <yourcustompermission>`` tag to every item in the gui.

https://shynixn.github.io/PetBlocks/build/html/customizing/samplehidingguiitems.html
