### ISSUE TITLE
Selecting new block in Head Database changes pet skin

### ISSUE THREAD

**Issue by incredimike** [Shynixn/PetBlocks#563]
I have the plugin Head Database 4.18.3 installed and any time I select a new head block from the plugin's menu plugin it changes my petblock skin.

Using PetBlocks 9.0.3

**Comment by Shynixn** [comment]
This behaviour is not ideal and happens with everyone with the ``petblocks.pet.headDatabaseInventoryHook`` permission.

It would be better to replace it with a new command ``/petblocks openheaddatabase`` which opens the HeadDatabase inventory to allow for pet skin selection. Opening the headdatabase inventory with the default headdatabase commands must not change the pet type.
